# Generated by Django 5.0.4 on 2024-04-30 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_review_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='name',
        ),
    ]
